### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by mgroth0** [hfhbd/kotlinx-serialization-csv#107]
"Missing attribute at $index in line $currentRow" is misleading because `currentRow`  might be different from the line number in the actual file due to headers and also because indexing starts at 0 while line numbers start at 1. For example, my error message was telling me the problem was at "line 77" so I wasted a lot of time try to find the issue in line 77 in my csv file when really the problem was in line 79.

**Comment by hfhbd** [comment]
Thanks for the feedback. What about the index? Is this helpful too?

**Comment by hfhbd** [comment]
Fixed by #109 and released in `0.0.12`.
