### ISSUE TITLE
How to convert dynamic columns or rows?

### ISSUE THREAD

**Issue by Goooler** [hfhbd/kotlinx-serialization-csv#171]
Here is the table format:

| key | values | values-zh |
|-----|--------|--------|
| key1 | first | 第一 |
| key2 | second | 第二 |
| key3 | third | 第三 | 

It's generated from Android res folder for multi-translation exporting, and the columns and rows are generated dynamically, I'm writing it to CSV or XLS row by row using [Apache POI](https://poi.apache.org), how can I do the same thing by this lib? Thanks!

**Comment by hfhbd** [comment]
Sorry, I have no idea what you want.

**Comment by Goooler** [comment]
Sorry for this, I just know how to finish it. Thanks!
