### ISSUE TITLE
Please add at least some examples of usage 

### ISSUE THREAD

**Issue by orchestr7** [hfhbd/kotlinx-serialization-csv#207]
I am using multiple different formats but this CSV library usage looks to be different from common way of implementation for such libs in kotlinx.serialization, so it would be great to have examples of usage in readme

**Comment by hfhbd** [comment]
Can you please elaborate what you mean with `looks different from common way`?
I agree [the readme does not contain many examples](https://github.com/hfhbd/kotlinx-serialization-csv/blob/main/kotlinx-serialization-csv/README.md), but on the other hand the lib is very simple.

**Comment by hfhbd** [comment]
> But actually it doesn't work

https://github.com/hfhbd/kotlinx-serialization-csv/blob/531003dfaa2842cead31de2e9fab2f26203fa2b5/kotlinx-serialization-csv/src/commonTest/kotlin/app/softwork/serialization/csv/CsvDecoderTest.kt#L131

Can you please add some configs or our environment? The format uses `\n` as line delimiter by default. You have to change it to `\r\n` if you use Windows (or files created on Windows).

**Comment by hfhbd** [comment]
Both usages are supported and not part of csv, but part of the core library. For generics support, you need to import the method from the core library.
