### ISSUE TITLE
New line character(s)

### ISSUE THREAD

**Issue by dellisd** [hfhbd/kotlinx-serialization-csv#33]
It looks like this implementation is hardcoded to use `\n` as the newline character, but on Windows files the newline is `\r\n` which can result in incorrect decoding.

e.g. if a number is in the last column, it is parsed as `0\r` which will throw a `NumberFormatException` when converted to an int.

**Comment by hfhbd** [comment]
Thanks, for CSV #36 will fix it. FLF is tracked in #35

**Comment by hfhbd** [comment]
Released in [0.0.3](https://github.com/hfhbd/kotlinx-serialization-csv/releases/tag/v0.0.3)
